dotnet pack src\core\StackExchange.Redis.Extensions.Core\StackExchange.Redis.Extensions.Core.csproj -o .\packages\ -c Release
dotnet pack src\serializers\StackExchange.Redis.Extensions.MsgPack\StackExchange.Redis.Extensions.MsgPack.csproj -o .\packages\ -c Release
dotnet pack src\serializers\StackExchange.Redis.Extensions.Newtonsoft\StackExchange.Redis.Extensions.Newtonsoft.csproj -o .\packages\ -c Release
dotnet pack src\serializers\StackExchange.Redis.Extensions.Protobuf\StackExchange.Redis.Extensions.Protobuf.csproj -o .\packages\ -c Release
dotnet pack src\serializers\StackExchange.Redis.Extensions.Utf8Json\StackExchange.Redis.Extensions.Utf8Json.csproj -o .\packages\ -c Release
dotnet pack src\serializers\StackExchange.Redis.Extensions.System.Text.Json\StackExchange.Redis.Extensions.System.Text.Json.csproj -o .\packages\ -c Release
dotnet pack src\serializers\StackExchange.Redis.Extensions.MemoryPack\StackExchange.Redis.Extensions.MemoryPack.csproj -o .\packages\ -c Release
dotnet pack src\serializers\StackExchange.Redis.Extensions.ServiceStack\StackExchange.Redis.Extensions.ServiceStack.csproj -o .\packages\ -c Release
dotnet pack src\compressors\StackExchange.Redis.Extensions.Compression.GZip\StackExchange.Redis.Extensions.Compression.GZip.csproj -o .\packages\ -c Release
dotnet pack src\compressors\StackExchange.Redis.Extensions.Compression.Brotli\StackExchange.Redis.Extensions.Compression.Brotli.csproj -o .\packages\ -c Release
dotnet pack src\compressors\StackExchange.Redis.Extensions.Compression.LZ4\StackExchange.Redis.Extensions.Compression.LZ4.csproj -o .\packages\ -c Release
dotnet pack src\compressors\StackExchange.Redis.Extensions.Compression.Snappier\StackExchange.Redis.Extensions.Compression.Snappier.csproj -o .\packages\ -c Release
dotnet pack src\compressors\StackExchange.Redis.Extensions.Compression.ZstdSharp\StackExchange.Redis.Extensions.Compression.ZstdSharp.csproj -o .\packages\ -c Release
dotnet pack src\aspnet\StackExchange.Redis.Extensions.AspNetCore\StackExchange.Redis.Extensions.AspNetCore.csproj -o .\packages\ -c Release
